### ISSUE TITLE
It would be handy if I could configure a few things.

### ISSUE THREAD

**Issue by schmidtw** [gizumon/github-actions-documenter#14]
This is a cool action.

It would be handy if there was a way to make a few things optional to make the documentation fit into existing documents a bit better:

- Make the table of contents and links optional.  I have several single workflow repositories that the extra formatting isn't needed.
- Allow the caller to specify a list of workflow yml files so if I want to document just one at a time, it's easy to do.  For example, I may document a workflow per markdown file.
- Make the `Generated automatically ... Please do not edit the below manually.` configurable as a comment instead.

I don't do much with typescript, but I could try to hack a patch together if that would help.  I'm not sure where to start for testing, though.

**Comment by gizumon** [comment]
Thank you for your comment and feedback.
I totally agree with your suggestions. Let me fix all of them in the next release version.

<br>

> I'm not sure where to start for testing, though.

You can debug in local with running `ts-node src/main.ts`. (I'll add this in node script as well in the next version.)

**Comment by gizumon** [comment]
Fixed in the latest release. Thank you for your feedback.
https://github.com/gizumon/github-actions-documenter/releases/tag/v0.2.1
