### ISSUE TITLE
Add Context Highlighting

### ISSUE THREAD

**Issue by schmidtw** [gizumon/github-actions-documenter#17]
It would be nice to have context highlighting since we're pretty sure the code block is going to be yaml format.

I think this is the place to add a trailing `yaml` to the existing ```.
https://github.com/gizumon/github-actions-documenter/blob/30da95d58b409d3a83915dac9af5a353cfc15410/src/markdown.ts#L28

**Comment by gizumon** [comment]
Fixed in the latest release. Thank you very much for your feedback.
https://github.com/gizumon/github-actions-documenter/releases/tag/v0.2.1
